# Generated by Django 6.0.4 on 2026-04-10 06:41

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('materia', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('apunte', 'Apunte'), ('parcial', 'Parcial resuelto'), ('clase', 'Clase particular'), ('noticia', 'Noticia'), ('proyecto', 'Proyecto'), ('link', 'Link de WhatsApp')], default='apunte', max_length=20)),
                ('anio', models.CharField(choices=[('1', '1er año'), ('2', '2do año'), ('3', '3er año'), ('4', '4to año'), ('5', '5to año')], default='1', max_length=1)),
                ('contenido', ckeditor.fields.RichTextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='posts/')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
